### ISSUE TITLE
Prusaslicer gcode export 0°C

### ISSUE THREAD

**Issue by LegionPleingaz** [jontek2/A-better-print_start-macro#10]
With prusa slicer, my gcode output was frozen to 0°C , my print didn't start at all

i had to modifiy the gcode:

DELETE: M104 S0 ; Stops PrusaSlicer from sending temp waits separately
DELETE: M140 S0
KEEP print_start EXTRUDER=[first_layer_temperature[initial_extruder]] BED=[first_layer_bed_temperature]

**Comment by cwoody81** [comment]
I am having an issue with it starting. I am using OrcaSlicer with Klipper running on a Voron Trident. 
Below is the error:

6:20 PM
Error evaluating 'gcode_macro PRINT_START:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'BED'
6:20 PM
Unknown command:"EXCLUDE_OBJECT_DEFINE"

**Comment by jontek2** [comment]
> I am having an issue with it starting. I am using OrcaSlicer with Klipper running on a Voron Trident. Below is the error:
> 
> 6:20 PM Error evaluating 'gcode_macro PRINT_START:gcode': jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'BED' 6:20 PM Unknown command:"EXCLUDE_OBJECT_DEFINE"

Sounds like you didn't do the required changes in your slicer. see https://github.com/jontek2/A-better-print_start-macro?tab=readme-ov-file#warning-required-changes-in-your-slicer-warning

**Comment by cwoody81** [comment]
I may have done them to well, I deleted everything in the slicer and added only what was in the GitHub notes for OrcaSlicer.

**Comment by jontek2** [comment]
If you're still having issues i'll suggest you open a help ticket in the Voron Design Discord. It will make troubleshooting easier! Thanks.
