### ISSUE TITLE
print_start as start_print kills bed plate. 

### ISSUE THREAD

**Issue by alihakkidemiral** [jontek2/A-better-print_start-macro#15]
accidently i change my printer profile on slicer. and my table wounded now :D because i use "print_start" name as script.  all slicers use start_print.

profile1 start gcode is :
```
M104 S0 ; Stops OrcaSlicer from sending temp waits separately
M140 S0
**PRINT_START** EXTRUDER=[first_layer_temperature] BED=[first_layer_bed_temperature] CHAMBER=[chamber_temperature] FILAMENT_TYPE="[filament_type]"
```

***************************************
profile2 start gcode is:
`**START_PRINT** EXTRUDER_TEMP=[nozzle_temperature_initial_layer] BED_TEMP=[bed_temperature_initial_layer_single]`

**Comment by jontek2** [comment]
Hey,

Ouch, scratching the bed doesn't sound ideal! Sorry to hear that. Make sure to update your other printer profiles.

Good luck on further printing and happy printing!
