### ISSUE TITLE
screws_tilt_adjust

### ISSUE THREAD

**Issue by rootiest** [jontek2/A-better-print_start-macro#3]
The main README page refers to the z_tilt operation on Trident as screw_tilt_adjust, [which is a different operation](https://www.klipper3d.org/Config_Reference.html#screws_tilt_adjust)

> Screw_tilt_adjust if your printer is a Trident

> Uncomment for Trident (screw_tilt_adjust)

Shouldn't that be [z_tilt_adjust](https://www.klipper3d.org/G-Codes.html#z_tilt_adjust) instead?

screws_tilt_adjust is used for probe-assisted manual bed leveling like on an Ender (with a probe)

**Comment by jontek2** [comment]
Good catch! The documentation has the wrong command but the macro the correct. I'll get it updated asap.
