### ISSUE TITLE
Control Bed Fans

### ISSUE THREAD

**Issue by airbornetrooper82573** [jontek2/A-better-print_start-macro#6]
I have 2 additional bed fans that can run separately from the nevermore. How would I go about controlling those with this print start macro?

**Comment by jontek2** [comment]
Hey!

Start by adding your  bed fans as a fan, something like:

`[output_pin bed_fans]
pin: XXX
value: 0
shutdown_value: 0`

Where XXX is your PIN on your controller.

Then you can add the following to your print_start macro to active the fans:

`SET_PIN PIN=bed_fans VALUE=1`

A good place to add that logic would be the Nevermore activates, it would look something like this:

    SET_PIN PIN=nevermore VALUE=1                      # Turns on the nevermore
    SET_PIN PIN=bed_fans VALUE=1                       # Turns on the bed fans

Don't forget to turn off the bed fans in your print_end macro with `SET_PIN PIN=bed_fans VALUE=0`

**Comment by airbornetrooper82573** [comment]
Thank you! I will add that to my config

**Comment by jontek2** [comment]
NP! I'll go ahead and close this issue.

Good luck and happy printing!
