### ISSUE TITLE
Set of circumstances with Tap that causes print failure

### ISSUE THREAD

**Issue by DavidCC00** [jontek2/A-better-print_start-macro#9]
If you follow the instructions for voron Tap's config alterations, have the printer cold, with bed temp below 90c and then use this macro, you'll get a "hotend too cold" error.  I moved hotend heating to after bed heating but before the 5 minute wait, that fixes the problem.  Adding a sufficient delay before it tries to QGL would probably also fix the issue.  I have a Dragon UHF which may also have contributed to finding this corner case, since it's more material to heat.

**Comment by jontek2** [comment]
Hey!

So the macro has a command called “M109 S150” which translate into “Set extruder temperature and wait: M109 [T<index>] S<temperature>” where M109 always waits for temperature to settle at requested value.

I’d double check your PID-tune to make sure that the hotend is keeping up with the set temperature of 150c.
